[package]
name = "wavetable_synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
shuffle = "0.1.7"
bitvec = "0.17.4"
rand = "0.8.4"
env = "0.0.0"

